In [52]:
from joblib import dump, load

In [53]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import neighbors, metrics

import numpy as np
import pandas as pd



In [54]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

In [55]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [57]:
data = pd.read_csv('car.data')
data.rename(columns = {'vhigh': 'buying', 'vhigh.1': 'maint', '2': 'doors', '2.1': 'persons', 'small': 'lug_boot', 'low': 'safety', 'unacc':'class'}, inplace = True)

In [58]:
data.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [59]:
X = data [['buying', 'maint', 'safety']].values
y = data[['class']].values

In [60]:
# Le = LabelEncoder()
# for i range(len(X[0])):

#     X[:, i] = Le.fit_transform(X)

In [61]:
y

array([['unacc'],
       ['unacc'],
       ['unacc'],
       ...,
       ['unacc'],
       ['good'],
       ['vgood']], dtype=object)

In [62]:
X = np.array([1,2,3,4,5,6,7])

In [63]:
X = X.reshape(-1, 1)

In [64]:
X.shape

(7, 1)

In [65]:
X

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [70]:
from sklearn import svm
iris = datasets.load_iris()

X = iris.data
y = iris.target

In [71]:
classes = ['Iris Setosa', 'Iris Veriscolour', 'Iris Virginica']

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2)

In [73]:
model = svm.SVC()
model.fit(X_train, y_train)

SVC()

In [75]:
from sklearn.metrics import accuracy_score
print(model)

SVC()


In [76]:
predictions = model.predict(X_test)
acc = accuracy_score(y_test, predictions)

print(predictions)
print(acc)

[1 1 1 2 2 2 0 0 1 2 0 2 2 2 0 1 1 2 2 0 2 2 0 1 0 1 1 1 0 1]
0.9333333333333333


In [78]:
for i in range(len(predictions)):
    print(classes[predictions[i]])

Iris Veriscolour
Iris Veriscolour
Iris Veriscolour
Iris Virginica
Iris Virginica
Iris Virginica
Iris Setosa
Iris Setosa
Iris Veriscolour
Iris Virginica
Iris Setosa
Iris Virginica
Iris Virginica
Iris Virginica
Iris Setosa
Iris Veriscolour
Iris Veriscolour
Iris Virginica
Iris Virginica
Iris Setosa
Iris Virginica
Iris Virginica
Iris Setosa
Iris Veriscolour
Iris Setosa
Iris Veriscolour
Iris Veriscolour
Iris Veriscolour
Iris Setosa
Iris Veriscolour


In [82]:
classes[predictions[3]]

'Iris Virginica'

In [85]:
classes[predictions[5]]

'Iris Virginica'

In [91]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
boston = datasets.load_boston()

In [87]:
X = boston.data
y = boston.target

In [99]:
jason = np.array([3,2])

In [100]:
jason.T

array([3, 2])

In [126]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
pd.Series(population_dict)

population_dict['Illinois']

12882135

In [121]:
for i in population_dict:
    print(population_dict[i])

38332521
26448193
19651127
19552860
12882135
